AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Node.js Lambda function for file management serverless apis
Resources:
  MyApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowOrigin: '''*'''
        AllowHeaders: '''*'''
        AllowMethods: '''OPTIONS,GET,POST,PUT,DELETE'''
        AllowCredentials: 'true'
    Metadata:
      SamResourceId: MyApiGateway
  MyLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: LambdaBasicExecutionPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
      - PolicyName: S3AccessPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:*
            Resource: '*'
    Metadata:
      SamResourceId: MyLambdaExecutionRole
  OrderFullFillmentServerLessDevServer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: OrderFullFillmentServerLessDevServer
      Handler: lambda.handler
      Role:
        Fn::GetAtt:
        - MyLambdaExecutionRole
        - Arn
      Runtime: nodejs18.x
      CodeUri: s3://order-fullfilment-app-lambda-server/ac97403b7829725f30eaff6751db1e2f
      MemorySize: 3008
      Timeout: 900
      Environment:
        Variables:
          DEBUG: app*
      Events:
        MainEntryRoute:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApiGateway
            Path: /
            Method: GET
        GetAllListImages:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApiGateway
            Method: PUT
            Path: /api/update-company-information
        UpdateImage:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApiGateway
            Method: POST
            Path: /api/uploadimageurl
    Metadata:
      SamResourceId: OrderFullFillmentServerLessDevServer
