AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Node.js Lambda function for file management serverless APIs

Resources:
  MyApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'*'"
        AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
        AllowCredentials: 'true'

  MyLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - s3:*
                Resource: "*"
  
  OrderFullFillmentServerLessDevServer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: OrderFullFillmentServerLessDevServer
      Handler: lambda.handler
      Role: !GetAtt MyLambdaExecutionRole.Arn
      Runtime: nodejs18.x
      CodeUri: .
      MemorySize: 3008
      Timeout: 900
      Environment:
        Variables:
          DEBUG: app*
      Events:
        MainEntryRoute:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /
            Method: GET
        UpdateCompanyInformation:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Method: PUT
            Path: "/api/update-company-information"
        GetCompanyInformation:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Method: GET
            Path: "/api/get-info"
        GetClientToken:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Method: GET
            Path: "/api/get-client-token"
        CreateCustomer:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Method: POST
            Path: "/api/create-customer"
        AddPaymentCard:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Method: POST
            Path: "/api/add-payment-card"
        GetCustomerDetails:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApiGateway
            Method: GET
            Path: /api/get-customer-details
        UploadOrdersExcel:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApiGateway
            Method: POST
            Path: /api/upload-order-excel
        viewAllOrders:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApiGateway
            Method: POST
            Path: /api/view-all-orders
        getProductDetails:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApiGateway
            Method: POST
            Path: /api/get-product-details
        getOrderPrice:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApiGateway
            Method: POST
            Path: /api/get-order-price
        lisShippingOptions:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApiGateway
            Method: POST
            Path: /api/shipping-options
        listVirtualInventory:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApiGateway
            Method: POST
            Path: /api/list-virtual-inventory
        updateVirtualInventory:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApiGateway
            Method: PUT
            Path: /api/update-virtual-inventory
        deleteVirtualInventory:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApiGateway
            Method: DELETE
            Path: /api/delete-virtual-inventory
        addProducts:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApiGateway
            Method: POST
            Path: /api/add-product