AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Node.js Lambda function for file management serverless APIs

Resources:
  ##################################
  # API Gateway
  ##################################
  MyApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'*'"
        AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
        AllowCredentials: 'true'

  ##################################
  # IAM Role
  ##################################
  MyLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - s3:*
                Resource: "*"

  ##################################
  # Main Lambda
  ##################################
  OrderFullFillmentServerLessDevServer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: OrderFullFillmentServerLessDevServer
      Handler: lambda.handler
      Role: !GetAtt MyLambdaExecutionRole.Arn
      Runtime: nodejs18.x
      CodeUri: .
      MemorySize: 3008
      Timeout: 900
      Environment:
        Variables:
          DEBUG: app*
      Events:
        MainEntryRoute:
          Type: Api 
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /
            Method: GET
        UpdateCompanyInformation:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/update-company-information
            Method: PUT
        GetCompanyInformation:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/get-info
            Method: GET
        GetClientToken:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/get-client-token
            Method: GET
        CreateCustomer:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/create-customer
            Method: POST
        AddPaymentCard:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/add-payment-card
            Method: POST
        GetCustomerDetails:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/get-customer-details
            Method: GET
        UploadOrdersExcel:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/upload-orders
            Method: POST
        ViewAllOrders:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/view-all-orders
            Method: POST
        ViewOrderDetails:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/view-order-details
            Method: POST
        UpdateOrders:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/update-orders
            Method: PUT
        UpdateOrdersByProduct:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/update-order-by-product
            Method: POST
        ValidateOrders:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/validate-orders
            Method: POST
        GetProductDetails:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/get-product-details
            Method: POST
        GetOrderPrice:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/get-order-price
            Method: POST
        ListShippingOptions:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/shipping-options
            Method: POST
        ListVirtualInventory:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/list-virtual-inventory
            Method: POST
        UpdateVirtualInventory:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/update-virtual-inventory
            Method: PUT
        DeleteVirtualInventory:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/delete-virtual-inventory
            Method: DELETE
        AddProducts:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/add-product
            Method: POST
        GetUserDetails:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/get-user-details
            Method: GET
        CreateNewOrder:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/create-new-order
            Method: POST
        DeleteOrder:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/delete-order
            Method: DELETE
        OrderSubmitStatus:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/order-submit-status
            Method: POST
        IncreaseProductQuantity:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/increase-product-quantity
            Method: POST
        AddTokenToUser:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/add-token-to-user
            Method: POST
        ExportToWoocommerce:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/export-to-woocommerce
            Method: POST
        GetUserPaymentToken:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/get-user-payment-tokens
            Method: GET
        ProcessVaultPayment:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/process-vaulted-payment
            Method: POST
        RemovePaymentMethod:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/remove-card
            Method: POST
        GetOrderDetailsById:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/get-order-details-by-id
            Method: POST
        SoftDeleteAfterPayment:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/soft-delete-after-payment
            Method: POST
        AccountDeactivation:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/disconnect
            Method: POST
        DisconnectProductFromInventory:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/disconnect-products-virtualInventory
            Method: POST
        GetCompanyInfo:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/get-company-info
            Method: GET
        UploadExcelOrder:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/upload-orders-from-excel
            Method: POST
        UpdateWithValidSKU:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/update-order-by-valid-product-sku
            Method: POST
        ConnectionEstablishment:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/connection-establishment
            Method: POST
        SubmitOrders:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/submit-orders-v2
            Method: POST
        TrashProduct:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/product-trashed
            Method: POST
        RestoreProduct:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/product-restored
            Method: POST
        ChangeSkuWoocomerce:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/product-sku-updated
            Method: POST
        CheckAccountKey:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/test-account-key
            Method: POST
        ListVirtualInventoryV2:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/list-virtual-inventory-v2
            Method: POST
        ConnectionFromOFA:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/connection-establishment-Ofa
            Method: POST
        CheckDomain:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/check-domain
            Method: POST
        OrderInformation:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/send-order-details
            Method: POST

  ##################################
  # V2 Lambda
  ##################################
  OrderFullFillmentServerLessDevServerV2:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: OrderFullFillmentServerLessDevServerV2
      Handler: lambda.handler
      Role: !GetAtt MyLambdaExecutionRole.Arn
      Runtime: nodejs18.x
      CodeUri: .
      MemorySize: 3008
      Timeout: 900
      Environment:
        Variables:
          DEBUG: app*
      Events:
        SendOrderInformation:
          Type: Api
          Properties:
            RestApiId: !Ref MyApiGateway
            Path: /api/send-order-information
            Method: POST

  ##################################
  # Wildcard Permissions (fixed /*/*)
  ##################################
  OrderFullFillmentServerLessDevServerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref OrderFullFillmentServerLessDevServer
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MyApiGateway}/*/*

  OrderFullFillmentServerLessDevServerV2Permission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref OrderFullFillmentServerLessDevServerV2
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MyApiGateway}/*/*

  ##################################
  # CloudWatch Logs
  ##################################
  OrderFullFillmentServerLessDevServerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${OrderFullFillmentServerLessDevServer}
      RetentionInDays: 30

  OrderFullFillmentServerLessDevServerV2LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${OrderFullFillmentServerLessDevServerV2}
      RetentionInDays: 30
