const { Router } = require('express');
const { updateCompanyInformation } = require('./update-company-information');
const { getCompanyInformation } = require('./get-company-information');
const { getClientToken, addPaymentCard, createCustomer, getFullCustomerDetails } = require('./payment-information');
const { uploadOrdersFromExcel, viewAllOrders, getOrderPrice, getProductDetails, listShippingOptions, validateOrders, validateSubmitOrders } = require('./upload-orders'); 
const { listVirtualInventory, validateListVirtualInventory, validateUpdateVirtualInventory, updateVirtualInventory, validateSkus, deleteVirtualInventory } = require('./virtual-inventory');
const { validateAddProduct, addProduct } = require('./products-management');
const app = Router();
app.put('/update-company-information',updateCompanyInformation);
app.get('/get-info', getCompanyInformation);
app.get('/get-user-details', getCompanyInformation);
app.get('/get-client-token', getClientToken);
app.post('/create-customer', createCustomer);
app.post('/add-payment-card', addPaymentCard);
app.get('/get-customer-details', getFullCustomerDetails);
app.post('/validate-orders', validateSubmitOrders, validateOrders);
app.post('/upload-orders', validateSubmitOrders, uploadOrdersFromExcel);
app.post('/get-order-price', getOrderPrice);
app.post('/get-product-details', getProductDetails);
app.post('/view-all-orders', viewAllOrders);
app.post('/shipping-options', listShippingOptions);
app.post('/list-virtual-inventory', validateListVirtualInventory, listVirtualInventory);
app.put('/update-virtual-inventory', validateUpdateVirtualInventory, updateVirtualInventory);
app.delete('/delete-virtual-inventory', validateSkus, deleteVirtualInventory);
app.post('/add-product', validateAddProduct, addProduct);
module.exports = app;